version: '3.4' 

services:

  silo:
    image: "${acrLoginServer}/silo:latest"
    #image: "silo:latest"
    build:
      context: .
      dockerfile: OrleansOnAppService.Silo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: silo
    ports:
      - 5000:80

  client:
    image: "${acrLoginServer}/client:latest"
    #image: "client:latest"
    build:
      context: .
      dockerfile: OrleansOnAppService.Client/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: client
    ports:
      - 5001:80

  dashboard:
    image: "${acrLoginServer}/dashboard:latest"
    #image: "dashboard:latest"
    build:
      context: .
      dockerfile: OrleansOnAppService.Dashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: dashboard
    ports:
      - 5002:80
